import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // `const { icon: _icon, ...rest } = house` drops fields on purpose.
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true }],
    },
  },
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by next-pwa and scripts/generate-panthers.mjs
    'public/sw.js',
    'public/workbox-*.js',
    'src/assets/panthers/index.ts',
    'scripts/.panther-preview/**',
  ]),
]);

export default eslintConfig;
